modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/nubxd11-lab/Big_Random_Mod"

[[mods]]
modId="playerevolutions"
version="${file.jarVersion}"
displayName="Mod Workshop"
logoFile="examplemod.png"

authors="AzzyAzimuth and nubxd11"
credits="Thanks to everyone who is involved in this project! We all had huge fun!"

description='''
This is the mod: Big Random Mod (mod_id = playerevolutions).
AzzyAzimuth and nubxd11 made many different fun things in this mod.
Refer to ReadMe for more details of everything added to the game.'''

[[dependencies.playerevolutions]]
modId="forge"
mandatory=true
versionRange="[31,)"
ordering="NONE"
side="BOTH"

[[dependencies.playerevolutions]]
modId="minecraft"
mandatory=true
versionRange="1.15.2"
ordering="NONE"
side="BOTH"
